### ISSUE TITLE
Possible Race condition

### ISSUE THREAD

**Issue by hardillb** [AlCalzone/node-coap-client#13]
I've been playing with this node to use as a base for a Node-RED node to work with the IKEA Tradfi light system.

I've got a little script I'm using to prototype the discovery phase and I'm running into occasional hangs that look to be a race condition somewhere. My setup has just 2 devices (a bulb and a dimmer), when the problem occurs I never get the response to the second `coap.request` call and after that even a call to `coap.reset` does not stop the processing of that second request.

```
const coap = require('node-coap-client').CoapClient;
const bonjour = require('bonjour')();

coap.setSecurityParams('192.168.1.111',{
  psk: {
    'Client_identity': 'xxxxxxxxxx'
  }
});

const deviceList = [];

bonjour.find({type: 'coap', protocol: 'udp'}, function(service){
  //console.log(service);
  var ip = service.addresses[0];
  coap.request('coaps://'+ ip + ':' + service.port + '//15001', 'get')
    .then( d => {
    //console.log("callback");
    //console.log(d.payload.toString());
    var devices = JSON.parse(d.payload.toString());
    devices.map(function(dd) {
      //console.log(dd);
      coap.request('coaps://'+ ip + ':'+ service.port + '//15001/'+ dd, 'get')
      .then(device => {
        var deviceDetails = JSON.parse(device.payload.toString());
        if (deviceDetails["5750"] === 2) {
          //console.log(JSON.parse(device.payload.toString()));
          deviceList.push({
            name: deviceDetails["9001"],
            ip: ip,
            port: service.port,
            deviceId: dd
          })
        }
      })
      .catch(err => {
        console.log(err);
      });
    });
  })
});

setTimeout(function(){
  console.log("shutdown");
  console.log(deviceList);
  coap.reset();
  bonjour.destroy();
},3000);
```

Debug trace -
```
$ DEBUG=node-coap-client node ikea.js 
  node-coap-client CoAP client version 0.4.4 +0ms
  node-coap-client getConnection(coaps://192.168.1.111:5684) => establishing new connection +166ms
  node-coap-client successfully created socket for origin coaps://192.168.1.111:5684 +110ms
  node-coap-client remembering request: msgID=1, token=efbfbdf0, url=coaps://192.168.1.111:5684//15001 +10ms
  node-coap-client added message to send queue, new length = 1 (high prio: 0) +0ms
  node-coap-client workOffSendQueue > concurrency = 0 (MAX 1) +2ms
  node-coap-client concurrency low enough, sending message 1 +0ms
  node-coap-client request 1: concurrency changed => 1 +0ms
  node-coap-client received message: ID=1, token=efbfbdf0 +15ms
  node-coap-client received ACK for 1, stopping retransmission... +4ms
  node-coap-client request 1: concurrency changed => 0 +0ms
  node-coap-client workOffSendQueue > queue empty +0ms
  node-coap-client getConnection(coaps://192.168.1.111:5684) => found existing connection +2ms
  node-coap-client getConnection(coaps://192.168.1.111:5684) => found existing connection +0ms
  node-coap-client remembering request: msgID=2, token=efbfbdf0, url=coaps://192.168.1.111:5684//15001/65537 +1ms
  node-coap-client added message to send queue, new length = 1 (high prio: 0) +0ms
  node-coap-client workOffSendQueue > concurrency = 0 (MAX 1) +1ms
  node-coap-client concurrency low enough, sending message 2 +0ms
  node-coap-client request 2: concurrency changed => 1 +0ms
  node-coap-client remembering request: msgID=3, token=efbfbdf0, url=coaps://192.168.1.111:5684//15001/65536 +1ms
  node-coap-client added message to send queue, new length = 1 (high prio: 0) +0ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
  node-coap-client received message: ID=2, token=efbfbdf0 +11ms
  node-coap-client received ACK for 2, stopping retransmission... +2ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +966ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +21ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +982ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +18ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +2ms
  node-coap-client retransmitting message 2, try #1 +610ms
  node-coap-client added message to send queue, new length = 2 (high prio: 0) +1ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
shutdown
[ { name: 'Living Room Light',
    ip: '192.168.1.111',
    port: 5684,
    deviceId: 65536 } ]
  node-coap-client closing connection to coaps://192.168.1.111:5684 +105ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +264ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +20ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +613ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +369ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +18ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +2ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +611ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +370ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +18ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +2ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +612ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +371ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +17ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +1ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +616ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +367ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +18ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +617ms
  node-coap-client retransmitting message 2, try #2 +214ms
  node-coap-client added message to send queue, new length = 3 (high prio: 0) +0ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +152ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +17ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +1ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +618ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +214ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +150ms
^C
```

**Comment by AlCalzone** [comment]
Thanks for the report. At a first glance there's two things going wrong:
```
node-coap-client remembering request: msgID=1, token=efbfbdf0, url=coaps://192.168.1.111:5684//15001 +10ms
node-coap-client remembering request: msgID=2, token=efbfbdf0, url=coaps://192.168.1.111:5684//15001/65537 +1ms
node-coap-client remembering request: msgID=3, token=efbfbdf0, url=coaps://192.168.1.111:5684//15001/65536 +1ms
```
The request tokens should differ for each request and:
```
node-coap-client received message: ID=2, token=efbfbdf0 +11ms
node-coap-client received ACK for 2, stopping retransmission... +2ms
node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +966ms
```
the ACK should reduce the concurrency, which it doesn't. 

I'll look into it.

**Comment by AlCalzone** [comment]
Hm, I can't reproduce both issues. I left out the bonjour bit from the test case, but the requests work as intended:
```
const coap = require('node-coap-client').CoapClient;

var ip = "192.168.2.110";
var port = 5684;
var host = `${ip}:${port}`;

coap.setSecurityParams(ip, {
    psk: {
        'Client_identity': 'XXXXXXXXXXXXXXXXXXXXX'
    }
});

const deviceList = [];

coap.request('coaps://' + host + '//15001', 'get')
    .then(d => {
        //console.log("callback");
        //console.log(d.payload.toString());
        var devices = JSON.parse(d.payload.toString());
        devices.map(function (dd) {
            //console.log(dd);
            coap.request('coaps://' + host + '//15001/' + dd, 'get')
                .then(device => {
                    var deviceDetails = JSON.parse(device.payload.toString());
                    if (deviceDetails["5750"] === 2) {
                        //console.log(JSON.parse(device.payload.toString()));
                        deviceList.push({
                            name: deviceDetails["9001"],
                            ip: ip,
                            port: port,
                            deviceId: dd
                        })
                    }
                })
                .catch(err => {
                    console.log(err);
                });
        });
    })

setTimeout(function () {
    console.log("shutdown");
    console.log(deviceList);
    coap.reset();
}, 3000);
```

The log looks like this (I have 2 bulbs, hence the extra requests):
```
  node-coap-client CoAP client version 0.4.6 +0ms
  node-coap-client getConnection(coaps://192.168.2.110:5684) => establishing new connection +4ms
  node-coap-client successfully created socket for origin coaps://192.168.2.110:5684 +32ms
  node-coap-client remembering request: msgID=1, token=e371b52f, url=coaps://192.168.2.110:5684//15001 +1ms
  node-coap-client added message to send queue, new length = 1 (high prio: 0) +1ms
  node-coap-client workOffSendQueue > concurrency = 0 (MAX 1) +0ms
  node-coap-client concurrency low enough, sending message 1 +0ms
  node-coap-client request 1: concurrency changed => 1 +0ms
  node-coap-client received message: ID=1, token=e371b52f +7ms
  node-coap-client received ACK for 1, stopping retransmission... +0ms
  node-coap-client request 1: concurrency changed => 0 +0ms
  node-coap-client workOffSendQueue > queue empty +1ms
  node-coap-client getConnection(coaps://192.168.2.110:5684) => found existing connection +0ms
  node-coap-client getConnection(coaps://192.168.2.110:5684) => found existing connection +0ms
  node-coap-client getConnection(coaps://192.168.2.110:5684) => found existing connection +1ms
  node-coap-client remembering request: msgID=2, token=e371b530, url=coaps://192.168.2.110:5684//15001/65537 +0ms
  node-coap-client added message to send queue, new length = 1 (high prio: 0) +0ms
  node-coap-client workOffSendQueue > concurrency = 0 (MAX 1) +0ms
  node-coap-client concurrency low enough, sending message 2 +2ms
  node-coap-client request 2: concurrency changed => 1 +0ms
  node-coap-client remembering request: msgID=3, token=e371b531, url=coaps://192.168.2.110:5684//15001/65536 +1ms
  node-coap-client added message to send queue, new length = 1 (high prio: 0) +1ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
  node-coap-client remembering request: msgID=4, token=e371b532, url=coaps://192.168.2.110:5684//15001/65538 +0ms
  node-coap-client added message to send queue, new length = 2 (high prio: 0) +0ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
  node-coap-client received message: ID=2, token=e371b530 +6ms
  node-coap-client received ACK for 2, stopping retransmission... +0ms
  node-coap-client request 2: concurrency changed => 0 +0ms
  node-coap-client workOffSendQueue > concurrency = 0 (MAX 1) +1ms
  node-coap-client concurrency low enough, sending message 3 +0ms
  node-coap-client request 3: concurrency changed => 1 +0ms
  node-coap-client received message: ID=3, token=e371b531 +60ms
  node-coap-client received ACK for 3, stopping retransmission... +0ms
  node-coap-client request 3: concurrency changed => 0 +1ms
  node-coap-client workOffSendQueue > concurrency = 0 (MAX 1) +0ms
  node-coap-client concurrency low enough, sending message 4 +0ms
  node-coap-client request 4: concurrency changed => 1 +0ms
  node-coap-client received message: ID=4, token=e371b532 +5ms
  node-coap-client received ACK for 4, stopping retransmission... +0ms
  node-coap-client request 4: concurrency changed => 0 +0ms
  node-coap-client workOffSendQueue > queue empty +0ms
  node-coap-client workOffSendQueue > queue empty +917ms
  node-coap-client workOffSendQueue > queue empty +10ms
  node-coap-client workOffSendQueue > queue empty +0ms
  node-coap-client workOffSendQueue > queue empty +1ms
  node-coap-client workOffSendQueue > queue empty +7ms
  node-coap-client workOffSendQueue > queue empty +61ms
shutdown
[ { name: 'TRADFRI bulb E27 WS opal 980lm',
    ip: '192.168.2.110',
    port: 5684,
    deviceId: 65537 },
  { name: 'TRADFRI bulb E27 WS opal 980lm 2',
    ip: '192.168.2.110',
    port: 5684,
    deviceId: 65538 } ]
  node-coap-client closing connection to coaps://192.168.2.110:5684 +2s
```
Notice how the tokens get incremented and each ACK reduces the concurrency. Please update node-coap-client to the newest version (although the issue should already be fixed in 0.4.4) and see if this resolves the problem. For reference, this is my dependency tree:
```
npm ls node-dtls-client
node-coap-bug@1.0.0 D:\test
`-- node-coap-client@0.4.6
  `-- node-dtls-client@0.2.1
```

**Comment by hardillb** [comment]
I've just updated to 0.4.6 and I'm still seeing the problem. It is intermittent maybe 1 in 3 attempts gets the same failure

```
$ DEBUG=node-coap-client node ikea.js 
  node-coap-client CoAP client version 0.4.6 +0ms
  node-coap-client getConnection(coaps://192.168.1.111:5684) => establishing new connection +151ms
  node-coap-client successfully created socket for origin coaps://192.168.1.111:5684 +70ms
  node-coap-client remembering request: msgID=1, token=2ddfbbf0, url=coaps://192.168.1.111:5684//15001 +4ms
  node-coap-client added message to send queue, new length = 1 (high prio: 0) +0ms
  node-coap-client workOffSendQueue > concurrency = 0 (MAX 1) +1ms
  node-coap-client concurrency low enough, sending message 1 +0ms
  node-coap-client request 1: concurrency changed => 1 +0ms
  node-coap-client received message: ID=1, token=2ddfbbf0 +7ms
  node-coap-client received ACK for 1, stopping retransmission... +0ms
  node-coap-client request 1: concurrency changed => 0 +1ms
  node-coap-client workOffSendQueue > queue empty +1ms
  node-coap-client getConnection(coaps://192.168.1.111:5684) => found existing connection +1ms
  node-coap-client getConnection(coaps://192.168.1.111:5684) => found existing connection +0ms
  node-coap-client remembering request: msgID=2, token=2ddfbbf0, url=coaps://192.168.1.111:5684//15001/65537 +1ms
  node-coap-client added message to send queue, new length = 1 (high prio: 0) +0ms
  node-coap-client workOffSendQueue > concurrency = 0 (MAX 1) +0ms
  node-coap-client concurrency low enough, sending message 2 +0ms
  node-coap-client request 2: concurrency changed => 1 +0ms
  node-coap-client remembering request: msgID=3, token=2ddfbbf0, url=coaps://192.168.1.111:5684//15001/65536 +0ms
  node-coap-client added message to send queue, new length = 1 (high prio: 0) +0ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
  node-coap-client received message: ID=2, token=2ddfbbf0 +6ms
  node-coap-client received ACK for 2, stopping retransmission... +0ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +985ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +10ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +1ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +992ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +9ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
  node-coap-client retransmitting message 2, try #1 +647ms
  node-coap-client added message to send queue, new length = 2 (high prio: 0) +1ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +345ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +7ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +1ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +648ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +345ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +8ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +648ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +345ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +8ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +649ms
shutdown
[ { name: 'Living Room Light',
    ip: '192.168.1.111',
    port: 5684,
    deviceId: 65536 } ]
  node-coap-client closing connection to coaps://192.168.1.111:5684 +136ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +209ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +8ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +650ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +344ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +7ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +651ms
  node-coap-client retransmitting message 2, try #2 +290ms
  node-coap-client added message to send queue, new length = 3 (high prio: 0) +0ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +1ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +52ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +7ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +653ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +289ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +52ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +6ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +2ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +654ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +287ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +51ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +8ms
  node-coap-client workOffSendQueue > concurrency = 1 (MAX 1) +0ms
^C
```

**Comment by AlCalzone** [comment]
Weird... I just ran the same command 10 times without problems. And your tokens still don't get incremented. Can you compare "build/CoapClient.js", lines 110ff if it looks like this?
```
function incrementToken(token) {
    var len = token.length;
    var ret = Buffer.alloc(len, token);
    for (var i = len - 1; i >= 0; i--) {
        if (ret[i] < 0xff) {
            ret[i]++;
            break;
        }
        else {
            ret[i] = 0;
            // continue with the next digit
        }
    }
    return ret;
}
```

**Comment by hardillb** [comment]
Yep, they look the same.

I've just moved this all over to a pi I have instead of my laptop to see if it's a nodejs version thing (4.8.4 on the laptop, 6.10.2 on the pi).

It's looking better on the pi, I've run it 10 times without a failure yet

**Comment by AlCalzone** [comment]
Oh! Thats it! Buffer.alloc was added in nodejs 5.10. 
I guess I'll mention NodeJS >= 6 as a requirement, since I'm not going to jump through hoops to support older versions.

**Comment by hardillb** [comment]
cool, Thanks for looking at this. I can get back to building the Node-RED goodness now.

You can add a `engines` block to the package.json which should flag this at install time

**Comment by AlCalzone** [comment]
Yeah I'll do that, thx!
